// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public interface AppointmentISDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appointment.AppointmentISD)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>bool status = 2;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>string diagnosis = 3;</code>
   * @return The diagnosis.
   */
  java.lang.String getDiagnosis();
  /**
   * <code>string diagnosis = 3;</code>
   * @return The bytes for diagnosis.
   */
  com.google.protobuf.ByteString
      getDiagnosisBytes();
}
