// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

/**
 * Protobuf type {@code appointment.AppointmentList}
 */
public  final class AppointmentList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:appointment.AppointmentList)
    AppointmentListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppointmentList.newBuilder() to construct.
  private AppointmentList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppointmentList() {
    appointments_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppointmentList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppointmentList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              appointments_ = new java.util.ArrayList<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj>();
              mutable_bitField0_ |= 0x00000001;
            }
            appointments_.add(
                input.readMessage(via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        appointments_ = java.util.Collections.unmodifiableList(appointments_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.class, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.Builder.class);
  }

  public static final int APPOINTMENTS_FIELD_NUMBER = 1;
  private java.util.List<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj> appointments_;
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  public java.util.List<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj> getAppointmentsList() {
    return appointments_;
  }
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  public java.util.List<? extends via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder> 
      getAppointmentsOrBuilderList() {
    return appointments_;
  }
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  public int getAppointmentsCount() {
    return appointments_.size();
  }
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj getAppointments(int index) {
    return appointments_.get(index);
  }
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder getAppointmentsOrBuilder(
      int index) {
    return appointments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < appointments_.size(); i++) {
      output.writeMessage(1, appointments_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < appointments_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, appointments_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList)) {
      return super.equals(obj);
    }
    via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList other = (via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList) obj;

    if (!getAppointmentsList()
        .equals(other.getAppointmentsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAppointmentsCount() > 0) {
      hash = (37 * hash) + APPOINTMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getAppointmentsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code appointment.AppointmentList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:appointment.AppointmentList)
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.class, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.Builder.class);
    }

    // Construct using via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAppointmentsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (appointmentsBuilder_ == null) {
        appointments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        appointmentsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentList_descriptor;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList getDefaultInstanceForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList build() {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList buildPartial() {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList result = new via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList(this);
      int from_bitField0_ = bitField0_;
      if (appointmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          appointments_ = java.util.Collections.unmodifiableList(appointments_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.appointments_ = appointments_;
      } else {
        result.appointments_ = appointmentsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList) {
        return mergeFrom((via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList other) {
      if (other == via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList.getDefaultInstance()) return this;
      if (appointmentsBuilder_ == null) {
        if (!other.appointments_.isEmpty()) {
          if (appointments_.isEmpty()) {
            appointments_ = other.appointments_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAppointmentsIsMutable();
            appointments_.addAll(other.appointments_);
          }
          onChanged();
        }
      } else {
        if (!other.appointments_.isEmpty()) {
          if (appointmentsBuilder_.isEmpty()) {
            appointmentsBuilder_.dispose();
            appointmentsBuilder_ = null;
            appointments_ = other.appointments_;
            bitField0_ = (bitField0_ & ~0x00000001);
            appointmentsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAppointmentsFieldBuilder() : null;
          } else {
            appointmentsBuilder_.addAllMessages(other.appointments_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj> appointments_ =
      java.util.Collections.emptyList();
    private void ensureAppointmentsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        appointments_ = new java.util.ArrayList<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj>(appointments_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder> appointmentsBuilder_;

    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public java.util.List<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj> getAppointmentsList() {
      if (appointmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(appointments_);
      } else {
        return appointmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public int getAppointmentsCount() {
      if (appointmentsBuilder_ == null) {
        return appointments_.size();
      } else {
        return appointmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj getAppointments(int index) {
      if (appointmentsBuilder_ == null) {
        return appointments_.get(index);
      } else {
        return appointmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder setAppointments(
        int index, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj value) {
      if (appointmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppointmentsIsMutable();
        appointments_.set(index, value);
        onChanged();
      } else {
        appointmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder setAppointments(
        int index, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder builderForValue) {
      if (appointmentsBuilder_ == null) {
        ensureAppointmentsIsMutable();
        appointments_.set(index, builderForValue.build());
        onChanged();
      } else {
        appointmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder addAppointments(via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj value) {
      if (appointmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppointmentsIsMutable();
        appointments_.add(value);
        onChanged();
      } else {
        appointmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder addAppointments(
        int index, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj value) {
      if (appointmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAppointmentsIsMutable();
        appointments_.add(index, value);
        onChanged();
      } else {
        appointmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder addAppointments(
        via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder builderForValue) {
      if (appointmentsBuilder_ == null) {
        ensureAppointmentsIsMutable();
        appointments_.add(builderForValue.build());
        onChanged();
      } else {
        appointmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder addAppointments(
        int index, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder builderForValue) {
      if (appointmentsBuilder_ == null) {
        ensureAppointmentsIsMutable();
        appointments_.add(index, builderForValue.build());
        onChanged();
      } else {
        appointmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder addAllAppointments(
        java.lang.Iterable<? extends via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj> values) {
      if (appointmentsBuilder_ == null) {
        ensureAppointmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, appointments_);
        onChanged();
      } else {
        appointmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder clearAppointments() {
      if (appointmentsBuilder_ == null) {
        appointments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        appointmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public Builder removeAppointments(int index) {
      if (appointmentsBuilder_ == null) {
        ensureAppointmentsIsMutable();
        appointments_.remove(index);
        onChanged();
      } else {
        appointmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder getAppointmentsBuilder(
        int index) {
      return getAppointmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder getAppointmentsOrBuilder(
        int index) {
      if (appointmentsBuilder_ == null) {
        return appointments_.get(index);  } else {
        return appointmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public java.util.List<? extends via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder> 
         getAppointmentsOrBuilderList() {
      if (appointmentsBuilder_ != null) {
        return appointmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(appointments_);
      }
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder addAppointmentsBuilder() {
      return getAppointmentsFieldBuilder().addBuilder(
          via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.getDefaultInstance());
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder addAppointmentsBuilder(
        int index) {
      return getAppointmentsFieldBuilder().addBuilder(
          index, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.getDefaultInstance());
    }
    /**
     * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
     */
    public java.util.List<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder> 
         getAppointmentsBuilderList() {
      return getAppointmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder> 
        getAppointmentsFieldBuilder() {
      if (appointmentsBuilder_ == null) {
        appointmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj.Builder, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder>(
                appointments_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        appointments_ = null;
      }
      return appointmentsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:appointment.AppointmentList)
  }

  // @@protoc_insertion_point(class_scope:appointment.AppointmentList)
  private static final via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList();
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppointmentList>
      PARSER = new com.google.protobuf.AbstractParser<AppointmentList>() {
    @java.lang.Override
    public AppointmentList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppointmentList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppointmentList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppointmentList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

