// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public interface AppointmentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appointment.AppointmentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool successful = 1;</code>
   * @return The successful.
   */
  boolean getSuccessful();
}
