// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public interface AppointmentListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appointment.AppointmentList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  java.util.List<via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj> 
      getAppointmentsList();
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObj getAppointments(int index);
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  int getAppointmentsCount();
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  java.util.List<? extends via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder> 
      getAppointmentsOrBuilderList();
  /**
   * <code>repeated .appointment.AppointmentObj appointments = 1;</code>
   */
  via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentObjOrBuilder getAppointmentsOrBuilder(
      int index);
}
