// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public final class AppointmentOuterClass {
  private AppointmentOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentISD_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentISD_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_AppointmentList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_AppointmentList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_RequestFindAppointmentsForDoctorObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_RequestFindAppointmentsForDoctorObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_appointment_RequestFindAppointmentsForPatientObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_appointment_RequestFindAppointmentsForPatientObj_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021appointment.proto\022\013appointment\"\202\001\n\016App" +
      "ointmentObj\022\n\n\002id\030\001 \001(\005\022\022\n\npatient_id\030\002 " +
      "\001(\005\022\021\n\tdoctor_id\030\003 \001(\005\022\014\n\004date\030\004 \001(\t\022\014\n\004" +
      "time\030\005 \001(\t\022\021\n\tdiagnosis\030\006 \001(\t\022\016\n\006status\030" +
      "\007 \001(\010\"\033\n\rAppointmentId\022\n\n\002id\030\001 \001(\005\",\n\016Ap" +
      "pointmentDto\022\014\n\004date\030\001 \001(\t\022\014\n\004time\030\002 \001(\t" +
      "\")\n\023AppointmentResponse\022\022\n\nsuccessful\030\001 " +
      "\001(\010\"?\n\016AppointmentISD\022\n\n\002id\030\001 \001(\005\022\016\n\006sta" +
      "tus\030\002 \001(\010\022\021\n\tdiagnosis\030\003 \001(\t\"D\n\017Appointm" +
      "entList\0221\n\014appointments\030\001 \003(\0132\033.appointm" +
      "ent.AppointmentObj\"?\n#RequestFindAppoint" +
      "mentsForDoctorObj\022\014\n\004date\030\001 \001(\t\022\n\n\002id\030\002 " +
      "\001(\005\"@\n$RequestFindAppointmentsForPatient" +
      "Obj\022\014\n\004date\030\001 \001(\t\022\n\n\002id\030\002 \001(\0052\264\005\n\013Appoin" +
      "tment\022G\n\013CreateAsync\022\033.appointment.Appoi" +
      "ntmentObj\032\033.appointment.AppointmentObj\022G" +
      "\n\014GetByIdAsync\022\032.appointment.Appointment" +
      "Id\032\033.appointment.AppointmentObj\022I\n\rGetBy" +
      "DtoAsync\022\033.appointment.AppointmentDto\032\033." +
      "appointment.AppointmentObj\022L\n\013UpdateAsyn" +
      "c\022\033.appointment.AppointmentObj\032 .appoint" +
      "ment.AppointmentResponse\022K\n\013DeleteAsync\022" +
      "\032.appointment.AppointmentId\032 .appointmen" +
      "t.AppointmentResponse\022k\n\031findAppointment" +
      "sForDoctor\0220.appointment.RequestFindAppo" +
      "intmentsForDoctorObj\032\034.appointment.Appoi" +
      "ntmentList\022m\n\032findAppointmentsForPatient" +
      "\0221.appointment.RequestFindAppointmentsFo" +
      "rPatientObj\032\034.appointment.AppointmentLis" +
      "t\022Q\n\025UpdateStatusDiagnosis\022\033.appointment" +
      ".AppointmentISD\032\033.appointment.Appointmen" +
      "tObjB6\n2via.sdj3.proofofconcept_v3.GrpcS" +
      "ervice.appointmentP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_appointment_AppointmentObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_appointment_AppointmentObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentObj_descriptor,
        new java.lang.String[] { "Id", "PatientId", "DoctorId", "Date", "Time", "Diagnosis", "Status", });
    internal_static_appointment_AppointmentId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_appointment_AppointmentId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_appointment_AppointmentDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_appointment_AppointmentDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentDto_descriptor,
        new java.lang.String[] { "Date", "Time", });
    internal_static_appointment_AppointmentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_appointment_AppointmentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentResponse_descriptor,
        new java.lang.String[] { "Successful", });
    internal_static_appointment_AppointmentISD_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_appointment_AppointmentISD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentISD_descriptor,
        new java.lang.String[] { "Id", "Status", "Diagnosis", });
    internal_static_appointment_AppointmentList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_appointment_AppointmentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_AppointmentList_descriptor,
        new java.lang.String[] { "Appointments", });
    internal_static_appointment_RequestFindAppointmentsForDoctorObj_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_appointment_RequestFindAppointmentsForDoctorObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_RequestFindAppointmentsForDoctorObj_descriptor,
        new java.lang.String[] { "Date", "Id", });
    internal_static_appointment_RequestFindAppointmentsForPatientObj_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_appointment_RequestFindAppointmentsForPatientObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_appointment_RequestFindAppointmentsForPatientObj_descriptor,
        new java.lang.String[] { "Date", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
