// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

/**
 * Protobuf type {@code appointment.AppointmentResponse}
 */
public  final class AppointmentResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:appointment.AppointmentResponse)
    AppointmentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AppointmentResponse.newBuilder() to construct.
  private AppointmentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AppointmentResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AppointmentResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AppointmentResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            successful_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.class, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.Builder.class);
  }

  public static final int SUCCESSFUL_FIELD_NUMBER = 1;
  private boolean successful_;
  /**
   * <code>bool successful = 1;</code>
   * @return The successful.
   */
  public boolean getSuccessful() {
    return successful_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (successful_ != false) {
      output.writeBool(1, successful_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (successful_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, successful_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse)) {
      return super.equals(obj);
    }
    via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse other = (via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse) obj;

    if (getSuccessful()
        != other.getSuccessful()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUCCESSFUL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccessful());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code appointment.AppointmentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:appointment.AppointmentResponse)
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.class, via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.Builder.class);
    }

    // Construct using via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      successful_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_AppointmentResponse_descriptor;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse getDefaultInstanceForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse build() {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse buildPartial() {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse result = new via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse(this);
      result.successful_ = successful_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse) {
        return mergeFrom((via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse other) {
      if (other == via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse.getDefaultInstance()) return this;
      if (other.getSuccessful() != false) {
        setSuccessful(other.getSuccessful());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean successful_ ;
    /**
     * <code>bool successful = 1;</code>
     * @return The successful.
     */
    public boolean getSuccessful() {
      return successful_;
    }
    /**
     * <code>bool successful = 1;</code>
     * @param value The successful to set.
     * @return This builder for chaining.
     */
    public Builder setSuccessful(boolean value) {
      
      successful_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool successful = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSuccessful() {
      
      successful_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:appointment.AppointmentResponse)
  }

  // @@protoc_insertion_point(class_scope:appointment.AppointmentResponse)
  private static final via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse();
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AppointmentResponse>
      PARSER = new com.google.protobuf.AbstractParser<AppointmentResponse>() {
    @java.lang.Override
    public AppointmentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AppointmentResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AppointmentResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AppointmentResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

