// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

public interface RequestFindAppointmentsForPatientObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appointment.RequestFindAppointmentsForPatientObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  java.lang.String getDate();
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();

  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  int getId();
}
