// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: appointment.proto

package via.sdj3.proofofconcept_v3.GrpcService.appointment;

/**
 * Protobuf type {@code appointment.RequestFindAppointmentsForPatientObj}
 */
public  final class RequestFindAppointmentsForPatientObj extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:appointment.RequestFindAppointmentsForPatientObj)
    RequestFindAppointmentsForPatientObjOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestFindAppointmentsForPatientObj.newBuilder() to construct.
  private RequestFindAppointmentsForPatientObj(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestFindAppointmentsForPatientObj() {
    date_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestFindAppointmentsForPatientObj();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestFindAppointmentsForPatientObj(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            date_ = s;
            break;
          }
          case 16: {

            id_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_RequestFindAppointmentsForPatientObj_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_RequestFindAppointmentsForPatientObj_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.class, via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.Builder.class);
  }

  public static final int DATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object date_;
  /**
   * <code>string date = 1;</code>
   * @return The date.
   */
  public java.lang.String getDate() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      date_ = s;
      return s;
    }
  }
  /**
   * <code>string date = 1;</code>
   * @return The bytes for date.
   */
  public com.google.protobuf.ByteString
      getDateBytes() {
    java.lang.Object ref = date_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      date_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 2;
  private int id_;
  /**
   * <code>int32 id = 2;</code>
   * @return The id.
   */
  public int getId() {
    return id_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, date_);
    }
    if (id_ != 0) {
      output.writeInt32(2, id_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, date_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, id_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj)) {
      return super.equals(obj);
    }
    via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj other = (via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj) obj;

    if (!getDate()
        .equals(other.getDate())) return false;
    if (getId()
        != other.getId()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATE_FIELD_NUMBER;
    hash = (53 * hash) + getDate().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code appointment.RequestFindAppointmentsForPatientObj}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:appointment.RequestFindAppointmentsForPatientObj)
      via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObjOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_RequestFindAppointmentsForPatientObj_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_RequestFindAppointmentsForPatientObj_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.class, via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.Builder.class);
    }

    // Construct using via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      date_ = "";

      id_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.AppointmentOuterClass.internal_static_appointment_RequestFindAppointmentsForPatientObj_descriptor;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj getDefaultInstanceForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj build() {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj buildPartial() {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj result = new via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj(this);
      result.date_ = date_;
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj) {
        return mergeFrom((via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj other) {
      if (other == via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj.getDefaultInstance()) return this;
      if (!other.getDate().isEmpty()) {
        date_ = other.date_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object date_ = "";
    /**
     * <code>string date = 1;</code>
     * @return The date.
     */
    public java.lang.String getDate() {
      java.lang.Object ref = date_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        date_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @return The bytes for date.
     */
    public com.google.protobuf.ByteString
        getDateBytes() {
      java.lang.Object ref = date_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        date_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string date = 1;</code>
     * @param value The date to set.
     * @return This builder for chaining.
     */
    public Builder setDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      date_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDate() {
      
      date_ = getDefaultInstance().getDate();
      onChanged();
      return this;
    }
    /**
     * <code>string date = 1;</code>
     * @param value The bytes for date to set.
     * @return This builder for chaining.
     */
    public Builder setDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      date_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>int32 id = 2;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 2;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:appointment.RequestFindAppointmentsForPatientObj)
  }

  // @@protoc_insertion_point(class_scope:appointment.RequestFindAppointmentsForPatientObj)
  private static final via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj();
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestFindAppointmentsForPatientObj>
      PARSER = new com.google.protobuf.AbstractParser<RequestFindAppointmentsForPatientObj>() {
    @java.lang.Override
    public RequestFindAppointmentsForPatientObj parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestFindAppointmentsForPatientObj(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestFindAppointmentsForPatientObj> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestFindAppointmentsForPatientObj> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.proofofconcept_v3.GrpcService.appointment.RequestFindAppointmentsForPatientObj getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

