// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

/**
 * Protobuf type {@code doctor.DoctorList}
 */
public  final class DoctorList extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:doctor.DoctorList)
    DoctorListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DoctorList.newBuilder() to construct.
  private DoctorList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DoctorList() {
    doctors_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DoctorList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DoctorList(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              doctors_ = new java.util.ArrayList<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj>();
              mutable_bitField0_ |= 0x00000001;
            }
            doctors_.add(
                input.readMessage(via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        doctors_ = java.util.Collections.unmodifiableList(doctors_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorOuterClass.internal_static_doctor_DoctorList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorOuterClass.internal_static_doctor_DoctorList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.class, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.Builder.class);
  }

  public static final int DOCTORS_FIELD_NUMBER = 1;
  private java.util.List<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj> doctors_;
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  public java.util.List<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj> getDoctorsList() {
    return doctors_;
  }
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  public java.util.List<? extends via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder> 
      getDoctorsOrBuilderList() {
    return doctors_;
  }
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  public int getDoctorsCount() {
    return doctors_.size();
  }
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj getDoctors(int index) {
    return doctors_.get(index);
  }
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder getDoctorsOrBuilder(
      int index) {
    return doctors_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < doctors_.size(); i++) {
      output.writeMessage(1, doctors_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < doctors_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, doctors_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList)) {
      return super.equals(obj);
    }
    via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList other = (via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList) obj;

    if (!getDoctorsList()
        .equals(other.getDoctorsList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDoctorsCount() > 0) {
      hash = (37 * hash) + DOCTORS_FIELD_NUMBER;
      hash = (53 * hash) + getDoctorsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code doctor.DoctorList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:doctor.DoctorList)
      via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorOuterClass.internal_static_doctor_DoctorList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorOuterClass.internal_static_doctor_DoctorList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.class, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.Builder.class);
    }

    // Construct using via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDoctorsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (doctorsBuilder_ == null) {
        doctors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        doctorsBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorOuterClass.internal_static_doctor_DoctorList_descriptor;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList getDefaultInstanceForType() {
      return via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.getDefaultInstance();
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList build() {
      via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList buildPartial() {
      via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList result = new via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList(this);
      int from_bitField0_ = bitField0_;
      if (doctorsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          doctors_ = java.util.Collections.unmodifiableList(doctors_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.doctors_ = doctors_;
      } else {
        result.doctors_ = doctorsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList) {
        return mergeFrom((via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList other) {
      if (other == via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList.getDefaultInstance()) return this;
      if (doctorsBuilder_ == null) {
        if (!other.doctors_.isEmpty()) {
          if (doctors_.isEmpty()) {
            doctors_ = other.doctors_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDoctorsIsMutable();
            doctors_.addAll(other.doctors_);
          }
          onChanged();
        }
      } else {
        if (!other.doctors_.isEmpty()) {
          if (doctorsBuilder_.isEmpty()) {
            doctorsBuilder_.dispose();
            doctorsBuilder_ = null;
            doctors_ = other.doctors_;
            bitField0_ = (bitField0_ & ~0x00000001);
            doctorsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDoctorsFieldBuilder() : null;
          } else {
            doctorsBuilder_.addAllMessages(other.doctors_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj> doctors_ =
      java.util.Collections.emptyList();
    private void ensureDoctorsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        doctors_ = new java.util.ArrayList<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj>(doctors_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder> doctorsBuilder_;

    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public java.util.List<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj> getDoctorsList() {
      if (doctorsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(doctors_);
      } else {
        return doctorsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public int getDoctorsCount() {
      if (doctorsBuilder_ == null) {
        return doctors_.size();
      } else {
        return doctorsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj getDoctors(int index) {
      if (doctorsBuilder_ == null) {
        return doctors_.get(index);
      } else {
        return doctorsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder setDoctors(
        int index, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj value) {
      if (doctorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDoctorsIsMutable();
        doctors_.set(index, value);
        onChanged();
      } else {
        doctorsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder setDoctors(
        int index, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder builderForValue) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.set(index, builderForValue.build());
        onChanged();
      } else {
        doctorsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder addDoctors(via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj value) {
      if (doctorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDoctorsIsMutable();
        doctors_.add(value);
        onChanged();
      } else {
        doctorsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder addDoctors(
        int index, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj value) {
      if (doctorsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDoctorsIsMutable();
        doctors_.add(index, value);
        onChanged();
      } else {
        doctorsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder addDoctors(
        via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder builderForValue) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.add(builderForValue.build());
        onChanged();
      } else {
        doctorsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder addDoctors(
        int index, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder builderForValue) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.add(index, builderForValue.build());
        onChanged();
      } else {
        doctorsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder addAllDoctors(
        java.lang.Iterable<? extends via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj> values) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, doctors_);
        onChanged();
      } else {
        doctorsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder clearDoctors() {
      if (doctorsBuilder_ == null) {
        doctors_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        doctorsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public Builder removeDoctors(int index) {
      if (doctorsBuilder_ == null) {
        ensureDoctorsIsMutable();
        doctors_.remove(index);
        onChanged();
      } else {
        doctorsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder getDoctorsBuilder(
        int index) {
      return getDoctorsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder getDoctorsOrBuilder(
        int index) {
      if (doctorsBuilder_ == null) {
        return doctors_.get(index);  } else {
        return doctorsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public java.util.List<? extends via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder> 
         getDoctorsOrBuilderList() {
      if (doctorsBuilder_ != null) {
        return doctorsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(doctors_);
      }
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder addDoctorsBuilder() {
      return getDoctorsFieldBuilder().addBuilder(
          via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.getDefaultInstance());
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder addDoctorsBuilder(
        int index) {
      return getDoctorsFieldBuilder().addBuilder(
          index, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.getDefaultInstance());
    }
    /**
     * <code>repeated .doctor.DoctorObj doctors = 1;</code>
     */
    public java.util.List<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder> 
         getDoctorsBuilderList() {
      return getDoctorsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder> 
        getDoctorsFieldBuilder() {
      if (doctorsBuilder_ == null) {
        doctorsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj.Builder, via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder>(
                doctors_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        doctors_ = null;
      }
      return doctorsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:doctor.DoctorList)
  }

  // @@protoc_insertion_point(class_scope:doctor.DoctorList)
  private static final via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList();
  }

  public static via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DoctorList>
      PARSER = new com.google.protobuf.AbstractParser<DoctorList>() {
    @java.lang.Override
    public DoctorList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DoctorList(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DoctorList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DoctorList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

