// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public interface DoctorListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doctor.DoctorList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  java.util.List<via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj> 
      getDoctorsList();
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObj getDoctors(int index);
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  int getDoctorsCount();
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  java.util.List<? extends via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder> 
      getDoctorsOrBuilderList();
  /**
   * <code>repeated .doctor.DoctorObj doctors = 1;</code>
   */
  via.sdj3.proofofconcept_v3.GrpcService.doctor.DoctorObjOrBuilder getDoctorsOrBuilder(
      int index);
}
