// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public final class DoctorOuterClass {
  private DoctorOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorObj_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorObj_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorUsername_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorUsername_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorVoid_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorVoid_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_doctor_DoctorLogin_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_doctor_DoctorLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014doctor.proto\022\006doctor\"x\n\tDoctorObj\022\n\n\002i" +
      "d\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\022\020\n\010password\030\003 " +
      "\001(\t\022\020\n\010fullname\030\004 \001(\t\022\026\n\016specialization\030" +
      "\005 \001(\t\022\021\n\tvalidated\030\006 \001(\010\"\"\n\016DoctorUserna" +
      "me\022\020\n\010username\030\002 \001(\t\"\026\n\010DoctorId\022\n\n\002id\030\001" +
      " \001(\005\"$\n\016DoctorResponse\022\022\n\nsuccessful\030\001 \001" +
      "(\010\"\014\n\nDoctorVoid\"0\n\nDoctorList\022\"\n\007doctor" +
      "s\030\001 \003(\0132\021.doctor.DoctorObj\"1\n\013DoctorLogi" +
      "n\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t2\223\003" +
      "\n\006Doctor\0223\n\013CreateAsync\022\021.doctor.DoctorO" +
      "bj\032\021.doctor.DoctorObj\022/\n\010GetAsync\022\020.doct" +
      "or.DoctorId\032\021.doctor.DoctorObj\0228\n\013Update" +
      "Async\022\021.doctor.DoctorObj\032\026.doctor.Doctor" +
      "Response\0227\n\013DeleteAsync\022\020.doctor.DoctorI" +
      "d\032\026.doctor.DoctorResponse\022;\n\021GetValidate" +
      "dAsync\022\022.doctor.DoctorVoid\032\022.doctor.Doct" +
      "orList\0227\n\rLoginAsDoctor\022\023.doctor.DoctorL" +
      "ogin\032\021.doctor.DoctorObj\022:\n\rGetByUsername" +
      "\022\026.doctor.DoctorUsername\032\021.doctor.Doctor" +
      "ObjB1\n-via.sdj3.proofofconcept_v3.GrpcSe" +
      "rvice.doctorP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_doctor_DoctorObj_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_doctor_DoctorObj_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorObj_descriptor,
        new java.lang.String[] { "Id", "Username", "Password", "Fullname", "Specialization", "Validated", });
    internal_static_doctor_DoctorUsername_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_doctor_DoctorUsername_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorUsername_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_doctor_DoctorId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_doctor_DoctorId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_doctor_DoctorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_doctor_DoctorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorResponse_descriptor,
        new java.lang.String[] { "Successful", });
    internal_static_doctor_DoctorVoid_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_doctor_DoctorVoid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorVoid_descriptor,
        new java.lang.String[] { });
    internal_static_doctor_DoctorList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_doctor_DoctorList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorList_descriptor,
        new java.lang.String[] { "Doctors", });
    internal_static_doctor_DoctorLogin_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_doctor_DoctorLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_doctor_DoctorLogin_descriptor,
        new java.lang.String[] { "Username", "Password", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
