// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public interface DoctorVoidOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doctor.DoctorVoid)
    com.google.protobuf.MessageOrBuilder {
}
