// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public interface DoctorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doctor.DoctorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool successful = 1;</code>
   * @return The successful.
   */
  boolean getSuccessful();
}
