// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: doctor.proto

package via.sdj3.proofofconcept_v3.GrpcService.doctor;

public interface DoctorObjOrBuilder extends
    // @@protoc_insertion_point(interface_extends:doctor.DoctorObj)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string username = 2;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 3;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string fullname = 4;</code>
   * @return The fullname.
   */
  java.lang.String getFullname();
  /**
   * <code>string fullname = 4;</code>
   * @return The bytes for fullname.
   */
  com.google.protobuf.ByteString
      getFullnameBytes();

  /**
   * <code>string specialization = 5;</code>
   * @return The specialization.
   */
  java.lang.String getSpecialization();
  /**
   * <code>string specialization = 5;</code>
   * @return The bytes for specialization.
   */
  com.google.protobuf.ByteString
      getSpecializationBytes();

  /**
   * <code>bool validated = 6;</code>
   * @return The validated.
   */
  boolean getValidated();
}
