// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient.proto

package via.sdj3.proofofconcept_v3.GrpcService.patient;

public interface NameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:patient.Name)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
